[package]
name = "rust-mandelbrot "
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["from"] }
pixels = "0.14.0"
winit = { version = "0.30.7", features = ["rwh_05"] }
